name: curious_cats
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.0.3
  fpdart: ^0.0.14
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  hive: ^2.2.1
  get_it: ^7.2.0
  logger: ^1.1.0
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  path_provider: ^2.0.10
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  all_lint_rules_community: ^0.0.9
  freezed: ^2.0.3+1
  build_runner: ^2.1.11
  mocktail: ^0.3.0
  retrofit_generator: ^4.0.1
  json_serializable: ^6.2.0
  hive_generator: ^1.1.3
  icons_launcher: ^1.1.8
  flutter_gen_runner: ^4.2.0
  bloc_test: ^9.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_intl:
  enabled: true
  class_name: GeneratedAppLocalizations
  arb_dir: lib/generated/localization/l10n
  output_dir: lib/generated/localization/generated

flutter_gen:
  output: lib/generated/flutter_gen/
  line_length: 100

  integrations:
    flutter_svg: true

flutter_icons:
  image_path: "assets/images/kitty_icon.png"
  ios: true
  android: true
  web: true
  macos: true
